FROM ruby:3.3.8-bookworm

RUN apt-get update -qq \
  && apt-get install --no-install-recommends -y curl postgresql-client \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY Gemfile Gemfile.lock ./
RUN bundle install
COPY . .

EXPOSE 3000
ENTRYPOINT ["bash", "bin/docker-entrypoint-dev"]
CMD ["bin/rails", "server", "-b", "0.0.0.0"]
