apiVersion: v1
kind: Service
metadata:
  name: book-reviews-web
  namespace: book-reviews
  labels:
    app.kubernetes.io/name: book-reviews
    app.kubernetes.io/component: web
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: book-reviews
    app.kubernetes.io/component: web
  ports:
    - name: http
      port: 80
      targetPort: http
      nodePort: 30080
      protocol: TCP
