apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: book-reviews-postgres-data
  namespace: book-reviews
  labels:
    app.kubernetes.io/name: book-reviews
    app.kubernetes.io/component: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
